name: s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy to s3
        run: >
          aws --endpoint-url $AWS_S3_ENDPOINT s3 sync ./public "s3://$AWS_S3_BUCKET"
          --follow-symlinks --acl public-read
          --include "*"
          --delete
        env:
          AWS_S3_BUCKET: upstream
          AWS_S3_ENDPOINT: https://s3.pl-waw.scw.cloud
          AWS_DEFAULT_REGION: pl-waw
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
